name: Build

on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build_release:
    name: Build Release
    needs: create_release
    environment: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
            compile_options: --target=bun-linux-x64-modern
          - os: macos-latest
            release_suffix: mac
            compile_options: --target=bun-darwin-arm64
          - os: macos-15
            release_suffix: mac_intel
            platform: x64
            compile_options: --target=bun-darwin-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - run: bun install
      - run: bun make:exe ${{ matrix.compile_options }}
      - name: Compress action step
        uses: a7ul/tar-action@v1.2.0
        id: compress
        with:
          command: c
          files: |
            ./exe
          outPath: slidesk.tar.gz
      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: cat ./slidesk.tar.gz > release_ubuntu.tar.gz
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: cat ./slidesk.tar.gz > release_mac.tar.gz
      - name: Run Mac Build
        if: matrix.os == 'macos-15'
        run: cat ./slidesk.tar.gz > release_mac_intel.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: release_${{ matrix.release_suffix }}.tar.gz

  generate_packages:
    name: Build packages file
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
      - name: Checkout code
        uses: actions/checkout@v4
      - run: bun install
      - run: bun make:exe
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          cp -p exe/* .debpkg/usr/bin/
      - name: build-deb-action
        uses: jiro4989/build-deb-action@v3
        with:
          package: "slidesk"
          desc: "Your presentation companion"
          arch: "amd64"
          package_root: ".debpkg"
          maintainer: "Sylvain Gougouzian <sylvain@gougouzian.fr>"
          version: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: slidesk_${{ github.ref_name }}_amd64.deb

  push_docker_hub:
    name: Push on Docker Hub
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    environment: build
    needs: build_release
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gouz/slidesk

      - name: Build and push Docker image (Amd64)
        if: matrix.os == 'ubuntu-latest'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/amd64/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (Arm64)
        if: matrix.os == 'macos-latest'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/arm64/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
